import { GoogleGenAI } from "@google/genai";
import { BOKLE_CONTEXT } from "../constants";

// Helper to check if configuration is present
export const checkConfiguration = (): boolean => {
    return !!process.env.API_KEY;
};

// Internal helper to get AI client initialized with API_KEY from process.env
const getAiClient = () => {
    if (!process.env.API_KEY) {
        throw new Error("MISSING_API_KEY");
    }
    return new GoogleGenAI({ apiKey: process.env.API_KEY });
};

const handleAiError = (error: any, context: string): string => {
    console.error(`Gemini API Error (${context}):`, error);
    return `Unable to generate content. Error: ${error.message || "Unknown error occurred."}`;
};

// Basic Text Task: 'gemini-3-flash-preview'
export const generateSalesScript = async (
    clientType: string,
    problem: string,
    stage: string
): Promise<string> => {
    try {
        const ai = getAiClient();
        const prompt = `
        TASK: Generate a sales script/guide for Gautam.
        CLIENT TYPE: ${clientType}
        ONE-LINE PROBLEM: ${problem}
        STAGE: ${stage}

        REQUIREMENTS:
        1. Exact opening lines.
        2. 3-4 Key Discovery Questions to ask.
        3. What answers to listen for (Green flags/Red flags).
        4. How to explain Bokle AI's relevant service simply.
        5. Objection handling for this specific client type.
        
        Keep it bulleted and actionable.
        `;

        const response = await ai.models.generateContent({
            model: "gemini-3-flash-preview",
            contents: prompt,
            config: {
                systemInstruction: `You are a strategic sales assistant for Bokle AI. \n${BOKLE_CONTEXT}`,
                temperature: 0.7,
            },
        });
        return response.text || "No response generated by the model.";
    } catch (error: any) {
        return handleAiError(error, "Sales Script");
    }
};

// Basic Text Task: 'gemini-3-flash-preview'
export const generateOutreachSequence = async (
    prospectName: string,
    role: string,
    company: string,
    painPoint: string
): Promise<string> => {
    try {
        const ai = getAiClient();
        const prompt = `
        TASK: Generate a personalized 4-step Cold Outreach Sequence for Gautam (Founder of Bokle AI).
        
        TARGET PROSPECT:
        Name: ${prospectName}
        Role: ${role}
        Company: ${company}
        Suspected Pain Point: ${painPoint}

        SEQUENCE REQUIREMENTS (Strict Format):
        You must use the exact headers below (starting with ## Step X:) so the system can parse them.

        ## Step 1: LinkedIn Connection Note
        (Max 300 chars. No subject. 2 short sentences. Friendly, peer-to-peer).

        ## Step 2: Cold Email 1
        Subject: [Write a catchy subject here]
        (Short, punchy body. Focus on ${painPoint}. Propose a solution, not a meeting).

        ## Step 3: LinkedIn Follow-up
        (If connected but no reply. Very short).

        ## Step 4: Cold Email 2 (The Bump)
        Subject: Re: [Previous Subject]
        (Value-add, sharing a quick idea or resource).

        TONE:
        - Founder-to-Founder (Peer level).
        - Professional but human.
        - NO marketing fluff ("Synergy", "Revolutionary").
        - Focus on "Gliding" (Ease of business).
        `;

        const response = await ai.models.generateContent({
            model: "gemini-3-flash-preview",
            contents: prompt,
            config: {
                systemInstruction: `You are a strategic sales assistant for Bokle AI. \n${BOKLE_CONTEXT}`,
                temperature: 0.7,
            },
        });
        return response.text || "No response generated by the model.";
    } catch (error: any) {
        return handleAiError(error, "Outreach Sequence");
    }
};

// Basic Text Task: 'gemini-3-flash-preview'
export const refineOutreachSequence = async (
    currentContent: string,
    instruction: string
): Promise<string> => {
    try {
        const ai = getAiClient();
        const prompt = `
        TASK: Rewrite the following Outreach Sequence based on the user's specific instructions.
        
        CURRENT CONTENT:
        ${currentContent}

        USER INSTRUCTIONS:
        "${instruction}"

        REQUIREMENTS:
        1. Maintain the "## Step X: [Type]" header structure so the UI stays consistent.
        2. Only modify what is requested.
        3. Maintain Bokle AI's founder-friendly tone.
        4. Return the FULL updated content.
        `;

        const response = await ai.models.generateContent({
            model: "gemini-3-flash-preview",
            contents: prompt,
            config: {
                systemInstruction: `You are an expert copywriter for Bokle AI. \n${BOKLE_CONTEXT}`,
                temperature: 0.7,
            },
        });
        return response.text || "No response generated.";
    } catch (error: any) {
        return handleAiError(error, "Refine Sequence");
    }
};

// Complex Text Task: 'gemini-3-pro-preview'
export const analyzeProspectList = async (
    csvData: string
): Promise<string> => {
    try {
        const ai = getAiClient();
        const prompt = `
        TASK: Analyze this list of prospects (exported from Apollo.io) and determine the Outreach Strategy.
        
        CSV DATA SAMPLE (First few rows):
        ${csvData}

        OUTPUT REQUIREMENTS:
        1. **ICP Analysis**: Who are these people? (e.g., "Mid-market E-commerce Founders").
        2. **Common Pain Points**: Based on their titles/industries, what likely keeps them up at night?
        3. **Strategy**: How should Bokle AI approach them? (e.g., "Lead with the 5-7 day delivery speed" or "Focus on Lead Scoring").
        4. **Hook**: Give me a 1-sentence "Hook" to use for this specific batch.
        `;

        const response = await ai.models.generateContent({
            model: "gemini-3-pro-preview",
            contents: prompt,
            config: {
                systemInstruction: `You are a strategic sales director for Bokle AI. \n${BOKLE_CONTEXT}`,
                temperature: 0.5,
            },
        });
        return response.text || "No analysis generated.";
    } catch (error: any) {
        return handleAiError(error, "List Analysis");
    }
};

// Basic Text Task with Google Search: 'gemini-3-flash-preview'
export const researchCompany = async (url: string): Promise<{ company: string, painPoint: string }> => {
    try {
        const ai = getAiClient();
        const prompt = `
        Research the company website: ${url}.
        
        I need you to extract or infer:
        1. The Company Name.
        2. A very short summary of what they do.
        3. A likely "Pain Point" that Bokle AI (AI Automation Agency) could solve for them.
        
        Bokle Services to match against:
        - Sales/Marketing AI (Lead scoring, chatbots)
        - Retail/Ecom AI (Product descriptions, pricing)
        
        Return ONLY a string in this specific format (do not use JSON, just text lines):
        Name: [Company Name]
        Summary: [1 sentence summary]
        PainPoint: [Likely pain point]
        `;

        const response = await ai.models.generateContent({
            model: "gemini-3-flash-preview",
            contents: prompt,
            config: {
                tools: [{googleSearch: {}}],
                systemInstruction: `You are a research assistant.`,
                temperature: 0.3,
            },
        });

        const text = response.text || "";
        
        // Simple parse
        const nameMatch = text.match(/Name:\s*(.*)/i);
        const ppMatch = text.match(/PainPoint:\s*(.*)/i);

        return {
            company: nameMatch ? nameMatch[1].trim() : "",
            painPoint: ppMatch ? ppMatch[1].trim() : ""
        };

    } catch (error: any) {
        console.error("Research Error:", error);
        return {
            company: "",
            painPoint: "Could not analyze URL automatically. Please enter details manually."
        };
    }
};

// Basic Text Task: 'gemini-3-flash-preview'
export const explainService = async (
    serviceName: string,
    clientContext: string
): Promise<string> => {
    try {
        const ai = getAiClient();
        const prompt = `
        TASK: Explain the service "${serviceName}" to a non-technical client (${clientContext}).
        
        REQUIREMENTS:
        1. Use plain business language.
        2. Focus on OUTCOMES (Time saved, Leads handled, Revenue increased).
        3. NO Tech jargon (No LLM, Vector DB, Python, API endpoints).
        4. Use the "Gliding" metaphor if appropriate (smooth, easy).
        5. Mention the 5-7 day delivery timeline.
        `;

        const response = await ai.models.generateContent({
            model: "gemini-3-flash-preview",
            contents: prompt,
            config: {
                systemInstruction: `You are a strategic sales assistant for Bokle AI. \n${BOKLE_CONTEXT}`,
                temperature: 0.7,
            },
        });
        return response.text || "No response generated by the model.";
    } catch (error: any) {
        return handleAiError(error, "Service Explainer");
    }
};

// Complex Text Task: 'gemini-3-pro-preview'
export const generateHandover = async (
    clientName: string,
    agreedScope: string,
    timeline: string
): Promise<string> => {
    try {
        const ai = getAiClient();
        const prompt = `
        TASK: Create an Internal Tech Team Handover Document.
        CLIENT: ${clientName}
        AGREED SCOPE (Business Terms): ${agreedScope}
        TIMELINE: ${timeline}

        OUTPUT FORMAT:
        1. **Summary**: One line technical summary.
        2. **Features/Requirements**: Translate the business scope into specific technical tasks (e.g., "Client needs a chatbot" -> "Implement RAG pipeline using provided PDF knowledge base").
        3. **Success Criteria**: What defines "Done".
        4. **Deadline**: Strict date based on timeline.
        
        NOTE: You are speaking to the developers now. Be precise.
        `;

        const response = await ai.models.generateContent({
            model: "gemini-3-pro-preview",
            contents: prompt,
            config: {
                systemInstruction: `You are a technical product manager for Bokle AI. \n${BOKLE_CONTEXT}`,
                temperature: 0.5,
            },
        });
        return response.text || "No response generated by the model.";
    } catch (error: any) {
        return handleAiError(error, "Handover");
    }
};

// Complex Text Task: 'gemini-3-pro-preview'
export const generateDocument = async (
    docType: 'Proposal' | 'ScopeOfWork' | 'Email',
    details: string
): Promise<string> => {
    try {
        const ai = getAiClient();
        console.log(`Starting generation for ${docType}...`);
        
        const prompt = `
        TASK: Generate a ${docType} for a client.
        DETAILS: ${details}

        REQUIREMENTS:
        - Tone: Professional, Calm, Trust-building (Bokle AI Brand).
        - Include Bokle AI's value of "Quality & Reliability" and "Ease of Integration".
        - If Proposal/SOW, clearly state the 5-7 day delivery promise if applicable.
        - Structure clearly with headers.
        `;

        const response = await ai.models.generateContent({
            model: "gemini-3-pro-preview",
            contents: prompt,
            config: {
                systemInstruction: `You are an operations assistant for Bokle AI. \n${BOKLE_CONTEXT}`,
                temperature: 0.7,
            },
        });
        
        return response.text || "Error: Empty response";
    } catch (error: any) {
        return handleAiError(error, "Document Generator");
    }
};

// Complex Text Task: 'gemini-3-pro-preview'
export const generateStageArtifact = async (
    stage: string,
    artifactType: string,
    clientName: string,
    context: string
): Promise<string> => {
    try {
        const ai = getAiClient();
        const prompt = `
        TASK: Generate a specific project artifact for the "${stage}" stage.
        ARTIFACT: ${artifactType}
        CLIENT: ${clientName}
        CONTEXT: ${context}

        INSTRUCTIONS:
        - Strictly follow the "STANDARD OPERATING PROCESS" format defined in your system instructions.
        - For BRD: Include Exec Summary, Problem, Objectives.
        - For SOW: Include Scope, Deliverables, Schedule.
        - For Project Charter: Include Goals, RACI, Timeline.
        - For Closure: Include Accomplishments, Lessons.
        - Be professional and ready to export to PDF.
        `;

        const response = await ai.models.generateContent({
            model: "gemini-3-pro-preview",
            contents: prompt,
            config: {
                systemInstruction: `You are a Delivery Manager for Bokle AI. \n${BOKLE_CONTEXT}`,
                temperature: 0.5,
            },
        });
        
        return response.text || "Error: Empty response";
    } catch (error: any) {
        return handleAiError(error, "Autopilot");
    }
};

// Basic Text Task: 'gemini-3-flash-preview'
export const refineArtifactContent = async (
    currentContent: string,
    instructions: string,
    artifactType: string
): Promise<string> => {
    try {
        const ai = getAiClient();
        const prompt = `
        TASK: Rewrite the following ${artifactType} based on the user's specific instructions.
        
        CURRENT CONTENT:
        ${currentContent}

        USER INSTRUCTIONS:
        "${instructions}"

        REQUIREMENTS:
        1. Keep the same structure unless asked to change it.
        2. Only modify what is requested or implied by the instruction.
        3. Maintain professional tone.
        4. Return the FULL updated document (not just the changed part).
        `;

        const response = await ai.models.generateContent({
            model: "gemini-3-flash-preview",
            contents: prompt,
            config: {
                systemInstruction: `You are an expert editor for Bokle AI. \n${BOKLE_CONTEXT}`,
                temperature: 0.7,
            },
        });
        return response.text || "No response generated.";
    } catch (error: any) {
        return handleAiError(error, "Refine Artifact");
    }
}

// Deprecated local storage key management removed per guidelines
export const saveApiKey = (key: string) => {};
export const removeApiKey = () => {};
export const getStoredApiKey = () => null;