
import { GoogleGenAI } from "@google/genai";
import { BOKLE_CONTEXT } from "../constants";

const getAiClient = () => {
    // API Key is injected by the environment
    const apiKey = process.env.API_KEY;
    if (!apiKey) {
        throw new Error("API_KEY is missing from process.env");
    }
    return new GoogleGenAI({ apiKey });
};

export const generateSalesScript = async (
    clientType: string,
    problem: string,
    stage: string
): Promise<string> => {
    try {
        const ai = getAiClient();
        const prompt = `
        TASK: Generate a sales script/guide for Gautam.
        CLIENT TYPE: ${clientType}
        ONE-LINE PROBLEM: ${problem}
        STAGE: ${stage}

        REQUIREMENTS:
        1. Exact opening lines.
        2. 3-4 Key Discovery Questions to ask.
        3. What answers to listen for (Green flags/Red flags).
        4. How to explain Bokle AI's relevant service simply.
        5. Objection handling for this specific client type.
        
        Keep it bulleted and actionable.
        `;

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
            config: {
                systemInstruction: `You are a strategic sales assistant for Bokle AI. \n${BOKLE_CONTEXT}`,
                temperature: 0.7,
            },
        });
        return response.text || "No response generated by the model.";
    } catch (error: any) {
        console.error("Gemini API Error (Sales Script):", error);
        return `Error generating script: ${error.message || "Unknown error"}`;
    }
};

export const generateOutreachSequence = async (
    prospectName: string,
    role: string,
    company: string,
    painPoint: string
): Promise<string> => {
    try {
        const ai = getAiClient();
        const prompt = `
        TASK: Generate a personalized 4-step Cold Outreach Sequence for Gautam (Founder of Bokle AI).
        
        TARGET PROSPECT:
        Name: ${prospectName}
        Role: ${role}
        Company: ${company}
        Suspected Pain Point: ${painPoint}

        SEQUENCE REQUIREMENTS:
        1. **LinkedIn Connection Note** (CRITICAL: MUST BE UNDER 300 CHARACTERS INCLUDING SPACES. Do not write a subject line. Just the message body. Keep it to 2 short sentences).
        2. **Cold Email 1** (Short, punchy, focus on ${painPoint}, propose a solution not a meeting).
        3. **LinkedIn Follow-up Message** (If connected but no reply).
        4. **Cold Email 2 (The "Bump")** (Value-add, sharing a quick idea or resource).

        TONE:
        - Founder-to-Founder (Peer level).
        - Professional but human.
        - NO marketing fluff ("Synergy", "Revolutionary").
        - Focus on "Gliding" (Ease of business).
        `;

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
            config: {
                systemInstruction: `You are a strategic sales assistant for Bokle AI. \n${BOKLE_CONTEXT}`,
                temperature: 0.7,
            },
        });
        return response.text || "No response generated by the model.";
    } catch (error: any) {
        console.error("Gemini API Error (Outreach Sequence):", error);
        return `Error generating sequence: ${error.message || "Unknown error"}`;
    }
};

export const analyzeProspectList = async (
    csvData: string
): Promise<string> => {
    try {
        const ai = getAiClient();
        const prompt = `
        TASK: Analyze this list of prospects (exported from Apollo.io) and determine the Outreach Strategy.
        
        CSV DATA SAMPLE (First few rows):
        ${csvData}

        OUTPUT REQUIREMENTS:
        1. **ICP Analysis**: Who are these people? (e.g., "Mid-market E-commerce Founders").
        2. **Common Pain Points**: Based on their titles/industries, what likely keeps them up at night?
        3. **Strategy**: How should Bokle AI approach them? (e.g., "Lead with the 5-7 day delivery speed" or "Focus on Lead Scoring").
        4. **Hook**: Give me a 1-sentence "Hook" to use for this specific batch.
        `;

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
            config: {
                systemInstruction: `You are a strategic sales director for Bokle AI. \n${BOKLE_CONTEXT}`,
                temperature: 0.5,
            },
        });
        return response.text || "No analysis generated.";
    } catch (error: any) {
        console.error("Gemini API Error (List Analysis):", error);
        return `Error analyzing list: ${error.message}`;
    }
};

export const explainService = async (
    serviceName: string,
    clientContext: string
): Promise<string> => {
    try {
        const ai = getAiClient();
        const prompt = `
        TASK: Explain the service "${serviceName}" to a non-technical client (${clientContext}).
        
        REQUIREMENTS:
        1. Use plain business language.
        2. Focus on OUTCOMES (Time saved, Leads handled, Revenue increased).
        3. NO Tech jargon (No LLM, Vector DB, Python, API endpoints).
        4. Use the "Gliding" metaphor if appropriate (smooth, easy).
        5. Mention the 5-7 day delivery timeline.
        `;

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
            config: {
                systemInstruction: `You are a strategic sales assistant for Bokle AI. \n${BOKLE_CONTEXT}`,
                temperature: 0.7,
            },
        });
        return response.text || "No response generated by the model.";
    } catch (error: any) {
        console.error("Gemini API Error (Service Explainer):", error);
        return `Error explaining service: ${error.message || "Unknown error"}`;
    }
};

export const generateHandover = async (
    clientName: string,
    agreedScope: string,
    timeline: string
): Promise<string> => {
    try {
        const ai = getAiClient();
        const prompt = `
        TASK: Create an Internal Tech Team Handover Document.
        CLIENT: ${clientName}
        AGREED SCOPE (Business Terms): ${agreedScope}
        TIMELINE: ${timeline}

        OUTPUT FORMAT:
        1. **Summary**: One line technical summary.
        2. **Features/Requirements**: Translate the business scope into specific technical tasks (e.g., "Client needs a chatbot" -> "Implement RAG pipeline using provided PDF knowledge base").
        3. **Success Criteria**: What defines "Done".
        4. **Deadline**: Strict date based on timeline.
        
        NOTE: You are speaking to the developers now. Be precise.
        `;

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
            config: {
                systemInstruction: `You are a technical product manager for Bokle AI. \n${BOKLE_CONTEXT}`,
                temperature: 0.5,
            },
        });
        return response.text || "No response generated by the model.";
    } catch (error: any) {
        console.error("Gemini API Error (Handover):", error);
        return `Error generating handover: ${error.message || "Unknown error"}`;
    }
};

export const generateDocument = async (
    docType: 'Proposal' | 'ScopeOfWork' | 'Email',
    details: string
): Promise<string> => {
    try {
        const ai = getAiClient();
        console.log(`Starting generation for ${docType}...`);
        
        const prompt = `
        TASK: Generate a ${docType} for a client.
        DETAILS: ${details}

        REQUIREMENTS:
        - Tone: Professional, Calm, Trust-building (Bokle AI Brand).
        - Include Bokle AI's value of "Quality & Reliability" and "Ease of Integration".
        - If Proposal/SOW, clearly state the 5-7 day delivery promise if applicable.
        - Structure clearly with headers.
        `;

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
            config: {
                systemInstruction: `You are an operations assistant for Bokle AI. \n${BOKLE_CONTEXT}`,
                temperature: 0.7,
            },
        });
        
        return response.text || "Error: Empty response";
    } catch (error: any) {
        console.error("Gemini API Error (Document Generator):", error);
        return `FAILED TO GENERATE DOCUMENT.\n\nError: ${error.message}`;
    }
};

export const generateStageArtifact = async (
    stage: string,
    artifactType: string,
    clientName: string,
    context: string
): Promise<string> => {
    try {
        const ai = getAiClient();
        const prompt = `
        TASK: Generate a specific project artifact for the "${stage}" stage.
        ARTIFACT: ${artifactType}
        CLIENT: ${clientName}
        CONTEXT: ${context}

        INSTRUCTIONS:
        - Strictly follow the "STANDARD OPERATING PROCESS" format defined in your system instructions.
        - For BRD: Include Exec Summary, Problem, Objectives.
        - For SOW: Include Scope, Deliverables, Schedule.
        - For Project Charter: Include Goals, RACI, Timeline.
        - For Closure: Include Accomplishments, Lessons.
        - Be professional and ready to export to PDF.
        `;

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
            config: {
                systemInstruction: `You are a Delivery Manager for Bokle AI. \n${BOKLE_CONTEXT}`,
                temperature: 0.5,
            },
        });
        
        return response.text || "Error: Empty response";
    } catch (error: any) {
        console.error("Gemini API Error (Autopilot):", error);
        return `FAILED TO GENERATE ARTIFACT.\n\nError: ${error.message}`;
    }
};
